### ISSUE TITLE
Server is running, but doesn't accept any incoming connections

### ISSUE THREAD

**Issue by BlueGradientHorizon** [hpi-swa/native-minecraft-server#6]
Hello. I've been trying to build native image of most recent minecraft server version 1.21.3 ([PaperMC](https://github.com/PaperMC/Paper)) and achieved some sort of success. The server is running, generating all of needed files, chunks, executing commands, etc, but it doesn't accept any connections. Nothing is being printed in the console.
Here's what I did to get a native executable:

0. I'm on Windows, and JFR isn't supported ([source](https://www.graalvm.org/latest/reference-manual/native-image/debugging-and-diagnostics/JFR/)):

> Note: JFR event recording is not yet available with Native Image on Windows.

But, interestingly, although I didn't enable it via passing cmd arguments to native-image, mc server was crashing.
<details>
<summary>Stacktrace</summary>

```
[18:27:55] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.isExcluded(Ljava/lang/Class;)Z [symbol: Java_jdk_jfr_internal_JVM_isExcluded or Java_jdk_jfr_internal_JVM_isExcluded__Ljava_lang_Class_2]
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:347) ~[org.bukkit.craftbukkit.main.exe:?]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:442) ~[org.bukkit.craftbukkit.main.exe:?]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2119) ~[org.bukkit.craftbukkit.main.exe:?]
	at net.minecraft.server.Main.main(Main.java:304) ~[?:?]
	at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[?:?]
	at org.bukkit.craftbukkit.Main.main(Main.java:281) ~[?:?]
	at java.base/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH) ~[?:?]
Caused by: java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.isExcluded(Ljava/lang/Class;)Z [symbol: Java_jdk_jfr_internal_JVM_isExcluded or Java_jdk_jfr_internal_JVM_isExcluded__Ljava_lang_Class_2]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152) ~[?:?]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41) ~[?:?]
	at jdk.jfr@24/jdk.jfr.internal.JVM.isExcluded(Native Method) ~[?:?]
	at jdk.jfr@24/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:139) ~[?:?]
	at jdk.jfr@24/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:134) ~[?:?]
	at jdk.jfr@24/jdk.jfr.FlightRecorder.register(FlightRecorder.java:129) ~[org.bukkit.craftbukkit.main.exe:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[org.bukkit.craftbukkit.main.exe:?]
	at net.minecraft.util.profiling.jfr.JfrProfiler.<init>(JfrProfiler.java:79) ~[?:?]
	at net.minecraft.util.profiling.jfr.JfrProfiler.<clinit>(JfrProfiler.java:79) ~[?:?]
	at net.minecraft.util.profiling.jfr.JvmProfiler.<clinit>(JvmProfiler.java:49) ~[org.bukkit.craftbukkit.main.exe:1.21.3-80-c2294d7]
	at net.minecraft.commands.Commands.<init>(Commands.java:225) ~[org.bukkit.craftbukkit.main.exe:1.21.3-80-c2294d7]
	at net.minecraft.server.ReloadableServerResources.<init>(ReloadableServerResources.java:41) ~[?:?]
	at net.minecraft.server.ReloadableServerResources.lambda$loadResources$1(ReloadableServerResources.java:85) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1196) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:556) ~[org.bukkit.craftbukkit.main.exe:?]
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:660) ~[org.bukkit.craftbukkit.main.exe:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:699) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:528) ~[org.bukkit.craftbukkit.main.exe:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[org.bukkit.craftbukkit.main.exe:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.runWith(Thread.java:1589) ~[org.bukkit.craftbukkit.main.exe:?]
	at java.base/java.lang.Thread.run(Thread.java:1576) ~[org.bukkit.craftbukkit.main.exe:?]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832) [org.bukkit.craftbukkit.main.exe:?]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808) [org.bukkit.craftbukkit.main.exe:?]
```
</details>

I solved this problem by creating a patch for PaperMC and compiling it from source.

<details>
<summary>Patch diff</summary>

```diff
From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: BlueGradientHorizon <safana53656@gmail.com>
Date: Mon, 2 Dec 2024 14:25:02 +0300
Subject: [PATCH] Don't use JFR on Windows for Native Image support


diff --git a/src/main/java/net/minecraft/util/profiling/jfr/JvmProfiler.java b/src/main/java/net/minecraft/util/profiling/jfr/JvmProfiler.java
index f381405ff5c84b3b15cedbbd940bdba61f36c4c0..67f79e0f936c6df412ac06a91db8c936a2f33d17 100644
--- a/src/main/java/net/minecraft/util/profiling/jfr/JvmProfiler.java
+++ b/src/main/java/net/minecraft/util/profiling/jfr/JvmProfiler.java
@@ -16,6 +16,7 @@ import org.slf4j.Logger;
 
 public interface JvmProfiler {
     JvmProfiler INSTANCE = (JvmProfiler)(Runtime.class.getModule().getLayer().findModule("jdk.jfr").isPresent()
+            && !System.getProperty("os.name").toLowerCase().contains("win")
         ? JfrProfiler.getInstance()
         : new JvmProfiler.NoOpProfiler());
```
</details>

1. Running the server bootstrapper for the first time to unpack libraries and patch official server with Paper patches
```
"C:\Program Files\graalvm-jdk-24+23.1\bin\java.exe" -jar paper-paperclip-1.21.3-R0.1-SNAPSHOT-mojmap.jar
```

2. Generating the list of needed libraries for classpath argument
```powershell
(ls .\libraries\ -Recurse -Include *.jar | % { $_.FullName }) -Split([Environment]::NewLine, [System.StringSplitOptions]::RemoveEmptyEntries) -join ";" > libraries.txt
```

3. Creating file `arg.txt` with classpath and main launch class
```
-cp versions\1.21.3\paper-1.21.3.jar;<contents of libraries.txt> org.bukkit.craftbukkit.Main
```

4. Running the server with metadata collection
```
"C:\Program Files\graalvm-jdk-24+23.1\bin\java.exe" -agentlib:native-image-agent=config-merge-dir=./,config-write-period-secs=10 @arg.txt nogui
```

5. Slight modifiing of `reachability-metadata.json`
By some reason, native image agent does not include all files of the data directory inside server jar into that file, but these are crucial for server to run, so replace:
```json
    {
      "glob": "data/.mcassetsroot"
    },
```
with
```json
    {
      "glob": "data/**"
    },
```

6. Building native image
```
"C:\Program Files\graalvm-jdk-24+23.1\bin\native-image.cmd" --no-fallback --report-unsupported-elements-at-runtime --initialize-at-run-time=io.netty -H:ConfigurationFileDirectories=./ --enable-url-protocols=http,https --initialize-at-build-time=net.minecraft.util.profiling.jfr.event,org.apache.logging.log4j,net.minecrell.terminalconsole.TCALookup @arg.txt
```

7. Running native executable
```
org.bukkit.craftbukkit.main.exe nogui
```
`nogui` is mandatory.

Any help is appreciated. I think I've gone far enough to not just give up.

[Modified Paper build (with my patch)](https://drive.google.com/file/d/1rgrPxFdZEkX7UrtnX7D27Dt3oJgYcbeh/view?usp=sharing)
[Windows x64 compiled binary](https://drive.google.com/file/d/1uK0VeK7aTDm1JTNCoA89LgodCiUMOB8K/view?usp=sharing)

**Comment by BlueGradientHorizon** [comment]
[Solved](https://github.com/oracle/graal/issues/10224#issuecomment-2522989911)
